authusers/urls.py
from django.urls import path,include
from . import views


app_name = 'authusers'

urlpatterns = [
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('log-out/',views.logout_view,name='logout'),
    path('changepass/',views.changepass1,name='user_change_pass'),
    path('user-profile/',views.user_profile, name='user-profile'),
    path('orders/', views.orders_views, name="user_orders"),
    path('order-detials/<int:id>', views.order_detail_view,name='order-detials')
]

coreapp/urls.py
from django.urls import path, include
from coreapp import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'coreapp'


StoreUrlPatterns=[
    # get product
    path("",views.store_listing__view, name='store-view'),
    path("<cid>/", views.store_listing__view, name="category-products"),
    
]

ProductUrlPatterns = [
    path('<pid>/', views.product__view, name='product-detials')
]

SearchUrlPatterns = [
    path('',views.search_item,name='search'),
]

AddToCartUrlPatterns = [
    
    path('',views.added_to_cart, name='add-to-cart'),
    
    
]

urlpatterns = [
    
    path('', views.index, name='index'),
    path('product/', include(ProductUrlPatterns)),
    path("store/", include(StoreUrlPatterns)),
    path('search/',include(SearchUrlPatterns)),
    path('add-to-cart/',include(AddToCartUrlPatterns)),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
    path('place-order/',views.checkout_view, name='checkout'),
    path('invoice/',views.invoice_view, name='invoice'),
    path('ajax-add-review/<int:pid>/',views.ajax_add_review, name='ajax-add-review'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('user/',include('authusers.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/base.html
{%load static%}
{% load humanize %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->

	<title>E commerce store</title>
	

	<!-- Google font -->
	<link href="https://fonts.googleapis.com/css?family=Montserrat:400,500,700" rel="stylesheet"/>

	<!-- Bootstrap -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}"/>

	<!-- Slick -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick.css' %}" />
	<link type="text/css" rel="stylesheet" href="{% static 'css/slick-theme.css' %}" />
	
	<!-- nouislider -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/nouislider.min.css' %}" />
	
	<!-- Font Awesome Icon -->
	<link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"/>
	
	<!-- Custom stlylesheet -->
	<link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}" />
	<link rel="stylesheet" href="{% static 'css/profile.css' %}">
	<link rel="stylesheet" type="text/css" media="all" href="{% static 'css/invoice.css' %}">
    {% comment %} <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css" integrity="sha512-+4zCK9k+qNFUR5X+cKL9EIR+ZOhtIloNl9GIKS57V1MyNsYpYcUrUeQc9vNfzsWfV28IaLL3i96P9sdNyeRssA==" crossorigin="anonymous" /> {% endcomment %}
	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	{% comment %} [if lt IE 9]>
		  <script src="{% static 'https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js' %}"></script>
		  <script src="{% static 'https://oss.maxcdn.com/respond/1.4.2/respond.min.js' %}"></script>
		<![endif] {% endcomment %}
	<script>src="{% static 'js/custom.js'%}"</script>
</head>

<body>

	<!-- HEADER -->
	<header>

		<!-- TOP HEADER -->
		<div id="top-header">
			<div class="container">
				<ul class="header-links pull-left">
					<li><a href="#"><i class="fa fa-phone"></i> +021-95-51-84</a></li>
					<li><a href="#"><i class="fa fa-envelope-o"></i> email@email.com</a></li>
					<li><a href="#"><i class="fa fa-map-marker"></i> 1734 Stonecoal Road</a></li>
				</ul>
				<ul class="header-links pull-right">
					<li><a href="#"><i class="fa fa-money"></i> PKR</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'authusers:user-profile' %}"><i class="fa fa-user-o"></i> {{user.username}}</a></li>
					<li><a href="{% url 'authusers:logout'%}"><i class="fa fa-sign-out"></i>logout</a></li>
					{% else %}
					<li><a href="{% url 'authusers:sign-in'%}"><i class="fa fa-user-o"></i>login</a></li>
					<li><a href="{% url 'authusers:sign-up'%}"><i class="fa fa-user-plus"></i>Sign Up</a></li>
					{% endif %}
					
				</ul>
			</div>
		</div>
		<!-- /TOP HEADER -->

		<!-- MAIN HEADER -->
		<div id="header">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					
					<!-- LOGO -->
					<div class="col-md-3">
						<div class="header-logo">
							<a href="#" class="logo">
								<img src="{% static './img/logo.png' %}" alt="">
							</a>
						</div>
					</div>
					<!-- /LOGO -->

					<!-- SEARCH BAR -->
					<div class="col-md-6">
						<div class="header-search">
							<form action="{% url 'coreapp:search' %}" method="GET">
								<select class="input-select">
									
									<option>All Categories</option> 
									<hr>
									{% comment %} {% if categories %}
									{% for cat in  categories %}
									<option>{{cat.name}}</option>
										
									{% endfor %}
									{% else %}
									<p><i>Categories not found</i></p>
										
									{% endif %}
										 {% endcomment %}
								</select> 
								<input class="input" placeholder="Search here" name="q">
								<button type='submit' class="search-btn">Search</button>
							</form>
						</div>
					</div>
					<!-- /SEARCH BAR -->

					<!-- ACCOUNT -->
					<div class="col-md-3 clearfix">
						<div class="header-ctn">
							<!-- Wishlist -->
							<div>
								<a href="#">
									<i class="fa fa-heart-o"></i>
									<span>Your Wishlist</span>
									<div class="qty">2</div>
								</a>
							</div>
							<!-- /Wishlist -->

							<!-- Cart -->
							<div class="dropdown">
								<a class="dropdown-toggle" data-toggle="dropdown" aria-expanded="true">
									<a href="{% url 'coreapp:cart' %}"><i class="fa fa-shopping-cart" ></i>
										<span>Your Cart</span>
										<div class="qty cart">{{ request.session.cart_data_obj|length}}</div></a>
								</a>
								{% comment %} <div class="cart-dropdown">
									<div class="cart-list">


										<div class="product-widget">
											<div class="product-img">
												<img src="{{item.image}}" alt="product image">
											</div>
											<div class="product-body">
												<h3 class="product-name"><a href="#">product name goes here</a></h3>
												<h4 class="product-price"><span class="qty">1x</span>$980.00</h4>
											</div>
											<button class="delete"><i class="fa fa-close"></i></button>
										</div>
											
											
									</div>
									<div class="cart-summary">
										<small>3 Item(s) selected</small>
										<h5>SUBTOTAL: $2940.00</h5>
									</div>
									<div class="cart-btns">
										<a href="#">View Cart</a>
										<a href="#">Checkout  <i class="fa fa-arrow-circle-right"></i></a>
									</div>
								</div> {% endcomment %}
							</div>
							<!-- /Cart -->

							<!-- Menu Toogle -->
							<div class="menu-toggle">
								<a href="#">
									<i class="fa fa-bars"></i>
									<span>Menu</span>
								</a>
							</div>
							<!-- /Menu Toogle -->
						</div>
					</div>
					<!-- /ACCOUNT -->
				</div>
				<!-- row -->
			</div>
			<!-- container -->
		</div>
		<!-- /MAIN HEADER -->
	</header>
	<!-- /HEADER -->

	<!-- NAVIGATION -->
	<nav id="navigation">
		<!-- container -->
		<div class="container">
			<!-- responsive-nav -->
			<div id="responsive-nav">
				<!-- NAV -->
				<ul class="main-nav nav navbar-nav">
					<li class="active"><a href="{% url 'coreapp:index' %}">Home</a></li>
					{% if categories %}
					{% for category in categories %}
					<li><a href="{% url 'coreapp:category-products' category.cid %}">{{category.name}}</a></li>
					{% endfor %} 
						{% else %}
					<li><a>Categories not found</a></li>
					{% endif %}
						
						
					
				</ul>
				<!-- /NAV -->
			</div>
			<!-- /responsive-nav -->
		</div>
		<!-- /container -->
	</nav>
	<!-- /NAVIGATION -->

	

	{% if messages %}
	{% for message in messages %}
	<div class="alert alert-{{message.tags}}"id="errorAlert" role="alert">
		<h5 style="text-align: center;">{{message}}</h5>
	</div>
	{% endfor %}
	{% endif %}

	
		
		

	{%block index%}{% endblock index%}
	
	{% block product_page %}{% endblock product_page %}
	
	{% block product_detail %}{% endblock product_detail %}
	
	{% block SearchProduct %}{% endblock SearchProduct %}
	
	{% block cart %}{% endblock cart %}
	
	{% block checkout %}{% endblock checkout %}

	{% block profile %}{% endblock profile %}
	
	{% block changepassword %}{% endblock changepassword %}\
	
	{% block orders %}{% endblock orders %}
		
	{% block invoice %}{% endblock invoice %}
		
		
		
		
		



	<!-- FOOTER -->
	<footer id="footer">
		<!-- top footer -->
		<div class="section">
			<!-- container -->
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">About Us</h3>
							<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor
								incididunt ut.</p>
							<ul class="footer-links">
								<li><a href="#"><i class="fa fa-map-marker"></i>1734 Stonecoal Road</a></li>
								<li><a href="#"><i class="fa fa-phone"></i>+021-95-51-84</a></li>
								<li><a href="#"><i class="fa fa-envelope-o"></i>email@email.com</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Categories</h3>
							<ul class="footer-links">
								<li><a href="#">Hot deals</a></li>
								<li><a href="#">Laptops</a></li>
								<li><a href="#">Smartphones</a></li>
								<li><a href="#">Cameras</a></li>
								<li><a href="#">Accessories</a></li>
							</ul>
						</div>
					</div>

					<div class="clearfix visible-xs"></div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Information</h3>
							<ul class="footer-links">
								<li><a href="#">About Us</a></li>
								<li><a href="#">Contact Us</a></li>
								<li><a href="#">Privacy Policy</a></li>
								<li><a href="#">Orders and Returns</a></li>
								<li><a href="#">Terms & Conditions</a></li>
							</ul>
						</div>
					</div>

					<div class="col-md-3 col-xs-6">
						<div class="footer">
							<h3 class="footer-title">Service</h3>
							<ul class="footer-links">
								<li><a href="#">My Account</a></li>
								<li><a href="#">View Cart</a></li>
								<li><a href="#">Wishlist</a></li>
								<li><a href="#">Track My Order</a></li>
								<li><a href="#">Help</a></li>
							</ul>
						</div>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /top footer -->

		<!-- bottom footer -->
		<div id="bottom-footer" class="section">
			<div class="container">
				<!-- row -->
				<div class="row">
					<div class="col-md-12 text-center">
						<ul class="footer-payments">
							<li><a href="#"><i class="fa fa-cc-visa"></i></a></li>
							<li><a href="#"><i class="fa fa-credit-card"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-paypal"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-mastercard"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-discover"></i></a></li>
							<li><a href="#"><i class="fa fa-cc-amex"></i></a></li>
						</ul>
						<span class="copyright">
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
							Copyright &copy;
							<script>document.write(new Date().getFullYear());</script> All rights reserved | This
							template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a
								href="https://colorlib.com" target="_blank">Colorlib</a>
							<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
						</span>
					</div>
				</div>
				<!-- /row -->
			</div>
			<!-- /container -->
		</div>
		<!-- /bottom footer -->
	</footer>
	<!-- /FOOTER -->

	<!-- jQuery Plugins -->
	<script src="{% static 'js/jquery.min.js' %}"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<script src="{% static 'js/slick.min.js' %}"></script>
	<script src="{% static 'js/nouislider.min.js' %}"></script>
	<script src="{% static 'js/jquery.zoom.min.js' %}"></script>
	<script src="{% static 'js/main.js' %}"></script>
	<script src="{% static 'js/custom.js' %}"></script>

	
	{% comment %} <script> src="{% static'js/Custom.js' %}"</script> {% endcomment %}
	

</body>

</html>