coreapp/urls.py
from django.urls import path, include
from coreapp import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'coreapp'


StoreUrlPatterns=[
    # get product
    path("",views.store_listing__view, name='store-view'),
    path("<cid>/", views.store_listing__view, name="category-products"),
    
]

ProductUrlPatterns = [
    path('<pid>/', views.product__view, name='product-detials')
]

SearchUrlPatterns = [
    path('',views.search_item,name='search'),
]

AddToCartUrlPatterns = [
    
    path('',views.added_to_cart, name='add-to-cart'),
    
    
]

urlpatterns = [
    
    path('', views.index, name='index'),
    path('product/', include(ProductUrlPatterns)),
    path("store/", include(StoreUrlPatterns)),
    path('search/',include(SearchUrlPatterns)),
    path('add-to-cart/',include(AddToCartUrlPatterns)),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
    path('place-order/',views.checkout_view, name='checkout'),
    path('invoice/',views.invoice_view, name='invoice'),
    path('ajax-add-review/<int:pid>/',views.ajax_add_review, name='ajax-add-review'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('user/',include('authusers.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

coreapp/models.py
from django.db import models 
from django.db.models import Count
from authusers.models import User
from shortuuid.django_fields import ShortUUIDField
# import os
from PIL import Image
from ckeditor_uploader.fields import RichTextUploadingField
from django.db import models, IntegrityError
from django.db.models import F
from django.db.models.constraints import UniqueConstraint, CheckConstraint




# Create your models here.


CHOICES = (
    ('Process', 'Processing'),
    ('Shipped', 'Shipped'),
    ('Delivered', 'Delivered'),
)

STATUS = (
    ('draft', 'Draft'),
    ('disabled', 'Disabled'),
    ('rejected', 'Rejected'),
    ('in_review', 'In Review'),
    ('publish', 'Published'),
)

RATING = (
    (1, '★☆☆☆☆'),
    (2, '★★☆☆☆'),
    (3, '★★★☆☆'),
    (4, '★★★★☆'),
    (5, '★★★★★'),
)


class BaseModel(models.Model):
    name = models.CharField(max_length=100, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True, null=True, blank=True)

    class Meta:
        abstract = True


class Category(BaseModel):
    
    cid = ShortUUIDField(unique=True, length=10, max_length=30,
                        prefix='cat', alphabet='abcdef12345')
    image = models.ImageField(upload_to='Category Images', null=True)
    # cat = models.Manager()

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name
    
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        print('\n\nActual Image size conversion--->>> ', img.size)

        # Resize the image as needed
        output_size = (200, 200)  # Set your desired size
        img = img.resize(output_size)
        print('Image size : --->>>',img.size)
        img.save(self.image.path)
        
# ------------------------------------ Product --------------------------


class Product(BaseModel):
    prod_image = models.ImageField(upload_to='Products', null=True)
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, default=None)

    pid = ShortUUIDField(unique=True, length=10, max_length=30,
                        prefix='scat', alphabet='abcdef12345')
    title = models.CharField(max_length=100, default='New Product')
    specification = RichTextUploadingField(
        null=True, blank=True, default='No description')
    description = RichTextUploadingField(max_length=500, blank=True)

    qty = models.PositiveIntegerField(default=0)
    warrenty = models.CharField(max_length=100, blank=True)
    price = models.DecimalField(
        max_digits=100, decimal_places=2, default=0.00)
    old_price = models.DecimalField(
        max_digits=100, decimal_places=2, default=0.00, blank=True)

    product_status = models.CharField(
        choices=STATUS, max_length=10, default='in_review')

    status = models.BooleanField(default=True)
    in_stock = models.BooleanField(default=True)

    sku = ShortUUIDField(unique=True, length=4, max_length=20,
                        prefix='sku', alphabet='1234567890')
    date = models.DateTimeField(auto_now_add=True) 

    # prod = models.Manager()

    class Meta:
        verbose_name_plural = 'Products'

    def __str__(self):
        return self.title

    def get_percentage(self):
        return (self.price/self.old_price) * 100
    
    # Resizing the image on upload
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.prod_image.path)
        print('\n\nActual Image size conversion--->>> ', img.size)

        # Resize the image as needed
        output_size = (600, 600)  # Set your desired size
        img = img.resize(output_size)
        print('Image size : --->>>',img.size)
        img.save(self.prod_image.path)


class ProductImages(models.Model):
    images = models.ImageField(upload_to='Product-Images')
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta: 
        verbose_name_plural = 'Product Images'
        
        # Resizing the image on upload
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.images.path)

        # Resize the image as needed
        output_size = (600, 600)  # Set your desired size
        img.thumbnail(output_size)
        img.save(self.images.path)

class ProductColor(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    color = models.CharField(unique=True,max_length=10, default='Red', blank=False)
    date = models.DateTimeField(auto_now_add=True)
    
    class Meta: 
        verbose_name_plural = 'Product Colors'

#############################################  Cart, Orders, OrderItems, Address ########################################################
#############################################  Cart, Orders, OrderItems, Address ########################################################
#############################################  Cart, Orders, OrderItems, Address ########################################################


class CartOrders(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    price = models.DecimalField(
        max_digits=100, decimal_places=3, default=0.00)
    payment_status = models.BooleanField(default=False)
    order_date = models.DateTimeField(auto_now_add=True)
    payment_type = models.CharField(max_length=10, blank=True)
    product_status = models.CharField(
        choices=CHOICES, max_length=30, default='Process')

    class Meta:
        verbose_name_plural = 'Cart Orders'
    def __str__(self):
        return f'Order-{self.id}'


class CartOrderItems(models.Model):
    order = models.ForeignKey(CartOrders, on_delete=models.CASCADE)
    product_id = models.IntegerField(blank=True)
    invoice_no = models.CharField(max_length=200)
    item = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    qty = models.PositiveIntegerField(default=0)
    color = models.CharField(max_length=10,blank=True)
    price = models.DecimalField(
        max_digits=100, decimal_places=2, default=0.00)
    total_amount = models.DecimalField(
        max_digits=100, decimal_places=2, default=0.00)

    class Meta:
        verbose_name_plural = 'Cart Ordered Items'

################################################# Product review, wishlist, Adderess #####################################
################################################# Product review, wishlist, Adderess #####################################
################################################# Product review, wishlist, Adderess #####################################


class ProductReview(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    review = models.TextField()
    ratings = models.IntegerField(choices=RATING, default=None)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Products Reviews'

    def __str__(self):
        return self.product.title

    def get_rating(self):
        return self.ratings

class Wishlist(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Wishlist'

    def __str__(self):
        return self.product.name

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    address = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=20, blank=True)
    country = models.CharField(max_length=20, blank=True)
    zip_code = models.CharField(max_length=10,blank=True)
    status = models.BooleanField(default=False)

    class Meta:
        verbose_name_plural = 'Address'

coreapp/forms.py
from django import forms
from coreapp.models import ProductReview


class ProductReviewForm(forms.ModelForm):
    review = forms.CharField(widget=forms.Textarea(attrs={'placeholder':'Write a Review'}))
    class Meta:
        model = ProductReview
        fields = ['review','ratings']

templates/coreapp/checkout.html
{% extends 'partials/base.html' %}
{% load static %}
{% block cart %}
  {% load humanize %}

  <!-- BREADCRUMB -->
  <div id="breadcrumb" class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-12">
          <h3 class="breadcrumb-header">Checkout</h3>
          <ul class="breadcrumb-tree">
            <li>
              <a href="#">Home</a>
            </li>
            <li class="active">Checkout</li>
          </ul>
        </div>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /BREADCRUMB -->

  <!-- SECTION -->
  <div class="section" id="cart-check-refresh">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <div class="col-md-7">
          <!-- Billing Details -->
          <div class="billing-details">
            <div class="section-title">
              <h3 class="title">Billing address</h3>
            </div>
            <div class="form-group">
              <input class="input" type="text" name="first-name" placeholder="First Name" />
            </div>
            <div class="form-group">
              <input class="input" type="text" name="last-name" placeholder="Last Name" />
            </div>
            <div class="form-group">
              <input class="input" type="email" name="email" placeholder="Email" />
            </div>
            <div class="form-group">
              <input class="input" type="text" name="address" placeholder="Address" />
            </div>
            <div class="form-group">
              <input class="input" type="text" name="city" placeholder="City" />
            </div>
            <div class="form-group">
              <input class="input" type="text" name="country" placeholder="Country" />
            </div>
            <div class="form-group">
              <input class="input" type="text" name="zip-code" placeholder="ZIP Code" />
            </div>
            <div class="form-group">
              <input class="input" type="tel" name="tel" placeholder="Telephone" />
            </div>
            <div class="form-group">
              <div class="input-checkbox">
                <input type="checkbox" id="create-account" />
                <label for="create-account">
                  <span></span>
                  Create Account?
                </label>
                <div class="caption">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt.</p>
                  <input class="input" type="password" name="password" placeholder="Enter Your Password" />
                </div>
              </div>
            </div>
          </div>
          <!-- /Billing Details -->
          <!-- Shiping Details -->
          <div class="shiping-details">
            <div class="section-title">
              <h3 class="title">Shiping address</h3>
            </div>
            <div class="input-checkbox">
              <input type="checkbox" id="shiping-address" />
              <label for="shiping-address">
                <span></span>
                Ship to a diffrent address?
              </label>
              <div class="caption">
                <div class="form-group">
                  <input class="input" type="text" name="first-name" placeholder="First Name" />
                </div>
                <div class="form-group">
                  <input class="input" type="text" name="last-name" placeholder="Last Name" />
                </div>
                <div class="form-group">
                  <input class="input" type="email" name="email" placeholder="Email" />
                </div>
                <div class="form-group">
                  <input class="input" type="text" name="address" placeholder="Address" />
                </div>
                <div class="form-group">
                  <input class="input" type="text" name="city" placeholder="City" />
                </div>
                <div class="form-group">
                  <input class="input" type="text" name="country" placeholder="Country" />
                </div>
                <div class="form-group">
                  <input class="input" type="text" name="zip-code" placeholder="ZIP Code" />
                </div>
                <div class="form-group">
                  <input class="input" type="tel" name="tel" placeholder="Telephone" />
                </div>
              </div>
            </div>
          </div>
          <!-- /Shiping Details -->

          <!-- Order notes -->
          <div class="order-notes">
            <textarea class="input" placeholder="Order Notes"></textarea>
          </div>
          <!-- /Order notes -->
        </div>
        <!-- Order Details -->
        <div class="col-md-5 order-details">
          <div class="section-title text-center">
            <h3 class="title">Your Order</h3>
          </div>
          <div class="order-summary">
            <hr />
            <div class="order-col">
              <div>
                <strong>No. of Products</strong>
              </div>
              <div>
                <strong>{{ totalCartItems }}</strong>
              </div>
            </div>
            <hr />
            <div class="order-col">
              <div>
                <strong>PRODUCT</strong>
              </div>
              <div>
                <strong>TOTAL</strong>
              </div>
            </div>

            <div class="order-products">
              {% if cart_data.items %}
                {% for product_id, item in cart_data.items %}
                  <div class="order-col">
                    <div>
                      {{ item.qty }} x <a href="{% url 'coreapp:product-detials' item.pid %}">{{ item.title }}</a> ({{ item.color }})
                    </div>
                    <div>
                      PKR{% widthratio item.price 1 item.qty %} <button class="delete-product" data-product="{{ product_id }}" style="border: none; background: transparent;"><i class="fa fa-trash" aria-hidden="true"></i></button>
                    </div>
                  </div>
                {% endfor %}
              {% else %}
                <h3>No products in cart</h3>
              {% endif %}
            </div>
            <hr />

            <div class="order-col">
              <div>Shiping</div>
              <div>
                <strong>FREE</strong>
              </div>
            </div>
            <hr />
            <div class="order-col">
              <div>
                <strong>TOTAL Amount</strong>
              </div>
              <div>
                <strong class="order-total">PKR.{{ TotalAmount|floatformat:2 }}</strong>
              </div>
            </div>
          </div>
          <h1>Payments Method</h1>
          <div class="payment-method">
            <div class="input-radio">
              <input type="radio" name="payment" id="payment-1">
              <label for="payment-1">
                <span></span>
                Cash on delivery
              </label>
              
            </div>
          </div>
          {% if totalCartItems %}
            <a href="{% url 'coreapp:checkout' %}" class="primary-btn order-submit">Place order</a>
            {% else %}
            <a href="{% url 'coreapp:index' %}" class="primary-btn order-submit">Back to shopping</a>
          {% endif %}

          <!-- /Order Details -->
        </div>
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
  <!-- /SECTION -->
{% endblock %}

templates/coreapp/product-listing.html
{% extends 'partials/base.html' %}
{% load static %}
{% load humanize %}
{% block product_page %}


<!-- BREADCRUMB -->
<div id="breadcrumb" class="section">
  <!-- container -->
  <div class="container">
    <!-- row -->
    <div class="row">
      <div class="col-md-12">
        <h3 class="breadcrumb-header">Shop</h3>
        <ul class="breadcrumb-tree">
          <li><a href="{% url 'coreapp:index' %}">Home</a></li>
          <li><a href="{% url 'coreapp:index' %}">Shop</a></li>
        </ul>
      </div>
    </div>
    <!-- /row -->
  </div>
  <!-- /container -->
</div>
<!-- /BREADCRUMB -->


  <div class="section">
    <!-- container -->
    <div class="container">
      <!-- row -->
      <div class="row">
        <!-- ASIDE -->
        <div id="aside" class="col-md-3">
          <!-- aside Widget -->
          <div class="aside">
            <h3 class="aside-title">brands</h3>
            <div class="checkbox-filter">
              {% if all_categories %}
                {% for category in all_categories %}
                  <div class="input-checkbox">
                    {% comment %} <input class="filter-checkbox" data-filter="{{category.cid}}" type="checkbox" id="category-2" /> {% endcomment %}
                    <label for="category-2">
                      <span></span>
                      <a href="{% url 'coreapp:category-products' category.cid %}">{{category.name}}</a>
                      <small>({{ category.product_set.count }})</small>
                    </label>
                  </div>
                {% endfor %}
              {% else %}
                <p>
                  <i>No Category found</i>
                </p>
              {% endif %}
            </div>
          </div>
          <!-- /aside Widget -->

          <!-- aside Widget -->
          {% comment %} <div class="aside">
            <h3 class="aside-title">Price</h3>
            <div class="price-filter">
              <div id="price-slider"></div>
              <div class="input-number price-min">
                <input id="price-min" type="number" />
                <span class="qty-up">+</span>
                <span class="qty-down">-</span>
              </div>
              <span>-</span>
              <div class="input-number price-max">
                <input id="price-max" type="number" />
                <span class="qty-up">+</span>
                <span class="qty-down">-</span>
              </div>
            </div>
          </div> {% endcomment %}
          <!-- /aside Widget -->

          <!-- aside Widget -->
          {% comment %} <div class="aside">
            <h3 class="aside-title">Brand</h3>
            <div class="checkbox-filter">
              <div class="input-checkbox">
                <input type="checkbox" id="brand-1" />
                <label for="brand-1">
                  <span></span>
                  SAMSUNG
                  <small>(578)</small>
                </label>
              </div>
              <div class="input-checkbox">
                <input type="checkbox" id="brand-2" />
                <label for="brand-2">
                  <span></span>
                  LG
                  <small>(125)</small>
                </label>
              </div>
              <div class="input-checkbox">
                <input type="checkbox" id="brand-3" />
                <label for="brand-3">
                  <span></span>
                  SONY
                  <small>(755)</small>
                </label>
              </div>
              <div class="input-checkbox">
                <input type="checkbox" id="brand-4" />
                <label for="brand-4">
                  <span></span>
                  SAMSUNG
                  <small>(578)</small>
                </label>
              </div>
              <div class="input-checkbox">
                <input type="checkbox" id="brand-5" />
                <label for="brand-5">
                  <span></span>
                  LG
                  <small>(125)</small>
                </label>
              </div>
              <div class="input-checkbox">
                <input type="checkbox" id="brand-6" />
                <label for="brand-6">
                  <span></span>
                  SONY
                  <small>(755)</small>
                </label>
              </div>
            </div>
          </div> {% endcomment %}
          <!-- /aside Widget -->

          <!-- aside Widget -->
          <div class="aside">
            <h3 class="aside-title">Top selling</h3>

            
            {% if top_products %}
            
            {% for product in top_products %}
              <div class="product-widget">
              <div class="product-img">
                <img src="{{product.prod_image.url}}" alt="{{product.title}}" />
              </div>
              <div class="product-body">
                <p class="product-category">{{product.category}}</p>
                <h3 class="product-name"><a href="{% url 'coreapp:product-detials' product.pid %}">{{product.title}}</a></h3>
                <h4 class="product-price">PKR.{{product.price}}
                {% if product.old_price != 0.00 %}
                <del class="product-old-price">PKR.{{product.old_price}}</del>
                {% endif %}
                  </h4>
              </div>
            </div>
            {% endfor %}
              
            {% else %}
            <h5>No products</h5>
              
            {% endif %}
              

          </div>
          <!-- /aside Widget -->
        </div>
        <!-- /ASIDE -->

        <!-- STORE -->
        <div id="store" class="col-md-9">
          <!-- store top filter -->
          {% comment %} <div class="store-filter clearfix">
            <div class="store-sort">
              <label>
                Sort By:<select class="input-select">
                  <option value="0">Popular</option>
                  <option value="1">Position</option>
                </select>
              </label>

              <label>
                Show:<select class="input-select">
                  <option value="0">20</option>
                  <option value="1">50</option>
                </select>
              </label>
            </div>
            <ul class="store-grid">
              <li class="active">
                <i class="fa fa-th"></i>
              </li>
              <li>
                <a href="#"><i class="fa fa-th-list"></i></a>
              </li>
            </ul>
          </div> {% endcomment %}
          <!-- /store top filter -->

          <!-- store products -->
          <div class="row">
            <!-- product -->

            {% if categories_with_products %}
              {% for product in categories_with_products %}
                <div class="col-md-4 col-xs-6">
                  <div class="product">
                    <div class="product-img">
                      <img src="{{ product.prod_image.url }}" alt="" />
                      <div class="product-label">
                        <span class="sale">-30%</span>
                        <span class="new">NEW</span>
                      </div>
                    </div>
                    <div class="product-body">
                      <p class="product-category">{{ product.category.name }}</p>
                      <h3 class="product-name"><a href="{% url 'coreapp:product-detials' product.pid %}">{{ product.title }}</a></h3>
                        {% if product.productcolor_set.all %}
                          <p class="product-color-" style="color: {{product.productcolor_set.all.0.color}}; background-color: black;" >Color: {{ product.productcolor_set.all.0.color }}</p>
                        {% endif %}
		
                          <h4 class="product-price">PKR <h3 class="product-price"
                          id="product-price-val-{{product.id}}"> {{ product.price  }} </h3> {% if product.old_price != 0.00 %}
                          <del class="product-old-price">PKR.{{product.old_price}}</del>
                          {% endif %}</h4>

                      <div class="product-rating">
                        {% if product.average_review > 0 %}
                          {% for s in product.average_review|ljust:product.average_review %}
                            <i class="fa fa-star"></i>
                          {% endfor %}
                        {% else %}
                          <i class="fa fa-star-o"></i>
                          <i class="fa fa-star-o"></i>
                          <i class="fa fa-star-o"></i>
                          <i class="fa fa-star-o"></i>
                          <i class="fa fa-star-o"></i>
                        {% endif %}
                      </div>
                      <div class="product-btns">
                        <button class="add-to-wishlist"><i class="fa fa-heart-o"></i><span class="tooltipp">add to wishlist</span></button>
                        <button class="add-to-compare"><i class="fa fa-exchange"></i><span class="tooltipp">add to compare</span></button>
                        <button class="quick-view"><i class="fa fa-eye"></i><span class="tooltipp">quick view</span></button>
                      </div>
                    </div>
                    <div class="add-to-cart">
						            <input type="hidden" class="Product-pid-{{ product.id }}"
                                            value="{{ product.pid }}">
                        <input type="hidden" class="Product-color-{{ product.id }}" value="{{ product.productcolor_set.all.0.color }}">

                        <input type="hidden" class="product-quantity-{{ product.id }}" value="1">
                        <input type="hidden" class="Product-image-{{ product.id }}"
                                            value="{{ product.prod_image.url }}">
                        <input type="hidden" class="Product-id-{{ product.id }}"
                                            value="{{ product.id }}">
                        <input type="hidden" class="Product-title-{{ product.id }}"
                                            value="{{ product.title }}">
                        <button class="add-to-cart-btn" data-index="{{ product.id }}"><i
                                                class="fa fa-shopping-cart"></i> add to cart</button>
                      
                    </div>
                  </div>
                </div>
              {% endfor %}
            {% else %}
              <h3>No products</h3>
            {% endif %}

            <!-- /product -->
          </div>
          <!-- /store products -->

          <!-- store bottom filter -->
          <div class="store-filter clearfix">
			<span class="store-qty">
			  Showing {{ categories_with_products.start_index }}-{{ categories_with_products.end_index }} of {{categories_with_products.paginator.count }} products
			</span>
			<ul class="store-pagination">
			  {% if categories_with_products.has_previous %}
			  <li>
				<a href="?page=1"><i class="fa fa-angle-left"></i></a>
			  </li>
			  {% endif %}
  
			  {% for page_num in categories_with_products.paginator.page_range %}
				<li {% if categories_with_products.number == page_num %}class="active" {% endif %}>
					<a href="?page={{ page_num }}">{{ page_num }}</a>
				</li>
				{% endfor %}
  
			  {% if categories_with_products.has_next %}
			  <li>
				<a href="?page={{ categories_with_products.paginator.num_pages }}"><i class="fa fa-angle-right"></i></a>
			  </li>
			  {% endif %}
		  </div>
          <!-- /store bottom filter -->
        </div>
        <!-- /STORE -->
      </div>
      <!-- /row -->
    </div>
    <!-- /container -->
  </div>
{% endblock %}