authusers/urls.py
from django.urls import path,include
from . import views


app_name = 'authusers'

urlpatterns = [
    path('sign-up/',views.register_view,name='sign-up'),
    path('sign-in/',views.login_view,name='sign-in'),
    path('log-out/',views.logout_view,name='logout'),
    path('changepass/',views.changepass1,name='user_change_pass'),
    path('user-profile/',views.user_profile, name='user-profile'),
    path('orders/', views.orders_views, name="user_orders"),
    path('order-detials/<int:id>', views.order_detail_view,name='order-detials')
]

coreapp/urls.py
from django.urls import path, include
from coreapp import views
from django.conf import settings
from django.conf.urls.static import static


app_name = 'coreapp'


StoreUrlPatterns=[
    # get product
    path("",views.store_listing__view, name='store-view'),
    path("<cid>/", views.store_listing__view, name="category-products"),
    
]

ProductUrlPatterns = [
    path('<pid>/', views.product__view, name='product-detials')
]

SearchUrlPatterns = [
    path('',views.search_item,name='search'),
]

AddToCartUrlPatterns = [
    
    path('',views.added_to_cart, name='add-to-cart'),
    
    
]

urlpatterns = [
    
    path('', views.index, name='index'),
    path('product/', include(ProductUrlPatterns)),
    path("store/", include(StoreUrlPatterns)),
    path('search/',include(SearchUrlPatterns)),
    path('add-to-cart/',include(AddToCartUrlPatterns)),
    path('cart/', views.cart_view, name='cart'),
    path('delete-from-cart/', views.delete_item_from_cart, name="delete-from-cart"),
    path('place-order/',views.checkout_view, name='checkout'),
    path('invoice/',views.invoice_view, name='invoice'),
    path('ajax-add-review/<int:pid>/',views.ajax_add_review, name='ajax-add-review'),
    
    
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

e_commerce_store/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('coreapp.urls')),
    path('user/',include('authusers.urls')),
    
    path('ckeditor/', include('ckeditor_uploader.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authusers/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.html import mark_safe
# Create your models here.



class User(AbstractUser):
    email = models.EmailField(unique=True)
    username = models.CharField(max_length=100)
    user_phone = models.CharField(max_length=15,null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    def __str__(self):
        return self.username
    
    # def catgory_image(self):
    #     return mark_safe('<img src="%s" width= "50px" height = "50px">' %(self.image.url))  # Corrected

authusers/forms.py
from .models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.core.validators import RegexValidator
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class SignUpForm(UserCreationForm):
    user_phone = forms.CharField(label='Phone number',required=True,help_text='Enter Phone number in this formate "03XXXXXXXXX"',validators=[RegexValidator(regex=r'^(\+92|0)?(3\d{9})$',
        message='Enter a valid Pakistan phone number.')])
   
    class Meta:
        model = User
        fields = ['username', 'first_name','last_name','email','user_phone']
        # labels = {'username': 'Username', 'first_name': 'First Name', 'last_name': 'Last Name', 'email':'Email Address'}



class CustomAuthenticationForm(AuthenticationForm):
        # Disable autocomplete for form fields
    username = forms.CharField(widget=forms.TextInput(attrs={'class': 'custom-class', 'autocomplete':'off'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'custom-class','autocomplete':'off'}))


class EditUserProfileForm(UserChangeForm):
    password = None
    class Meta:
        model = User
        fields =['username','first_name','last_name','email','user_phone','date_joined','last_login']
        labels = {'email':'Email'}


# class EditAdminProfileForm(UserChangeForm):
#     password = None
#     class Meta:
#         model = Users
#         fields ='__all__'
#         labels = {'email':'Email'}

authusers/views.py
from django.shortcuts import render,redirect,HttpResponseRedirect
from authusers.models import User
from .forms import SignUpForm, CustomAuthenticationForm, EditUserProfileForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import login, authenticate,logout,update_session_auth_hash
from django.contrib import messages
from coreapp.models import CartOrders, CartOrderItems, Address
# Create your views here.

def register_view(request):
    if request.method == 'POST':
        # print("----------------> getting the request", dict(request.POST.items()))
        # request_data = dict(request.POST.items())
        form = SignUpForm(request.POST or None)

        # print('Boolean------>',request_data is form.data)
        # print('Form Data: ', form.data)
        if form.is_valid():
            return _extracted_from_register_view_10(form, request)
    else:
        form = SignUpForm()

    context = {
        'form':form
    }
    return render(request,'authusers/signup.html',context)


# TODO Rename this here and in `register_view`
def _extracted_from_register_view_10(form, request):
    form.save()
    print('-----------> User regitsered')
    username = form.cleaned_data.get('username')
    messages.success(request, f'Hey {username}, Your Account created Successfully!')

    new_user = authenticate(username=form.cleaned_data['email'],
                            password=form.cleaned_data['password1'])
    login(request,new_user)
    return redirect('/')

def login_view(request):
    if request.user.is_authenticated and request.user.is_superuser:
        return redirect('/')
    if request.method == "POST":
        form = CustomAuthenticationForm(request=request, data=request.POST)
        # print(form.data)
        # print(form.errors)
        if form.is_valid():
            u_name = form.cleaned_data['username']
            u_pass = form.cleaned_data['password']
            user = authenticate(email=u_name, password=u_pass)
            if user is not None:
                login(request, user)
                messages.success(request, 'User login Succeessfully!')
                return HttpResponseRedirect('/')
        else:
            print('You are not authorized')
            messages.error(request, 'You are not authorized, Please Create the Account to login')
                
    else:
        form = CustomAuthenticationForm()           
    return render(request, 'authusers/login.html',{'form':form})

@login_required
def user_profile(request):
    if request.method == "POST":
        form = EditUserProfileForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            messages.success(request, 'User Updated Successfully!')
            update_session_auth_hash(request, form.user)  # Update the session to avoid logout
    else:
        form = EditUserProfileForm(instance=request.user)
    
    return render(request, 'authusers/profile.html', {'form': form})


def logout_view(request):
    logout(request)
    messages.success(request, "Logout successfully!")
    return redirect('/')

def changepass1 (request):
    if request.user.is_authenticated:
        if request.method =="POST":
            form = SetPasswordForm(user= request.user,data=request.POST)
            if form.is_valid():
                form.save()
                #This function is user to maintain the session for the user.
                update_session_auth_hash(request,form.user)
                messages.info(request,'Password Saved Successfully!')
                return redirect('authusers:user_change_pass')
        else:
            form = PasswordChangeForm(user=request.user)
        return render(request,'authusers/changepassword.html',{"form": form})
    else:
        messages.error(request,'You have no rights to access this page!')
        return redirect('authusers:sign-up')
    

def orders_views(request):
    if request.user.is_authenticated:
        orders = CartOrders.objects.filter( user=request.user).order_by('-id')
        return render(request,'authusers/orders.html',{'orders':orders})
    else:
        messages.error(request,"Please login First to proceed with your order")
        return redirect('authusers:sign-in')

def order_detail_view(request,id):
    if request.user.is_authenticated:
        order = CartOrders.objects.get(user=request.user,id=id)
        products = CartOrderItems.objects.filter(order=order)
        print(f"order items: {products.values()}")
        return render(request, 'authusers/orderdetails.html', {'products':products})  
    else:
        messages.error(request, "Please Login first to see the Orders Details")
        

def create_address(request):
    if request.user.is_authenticated:
        addresss = Address.objects.filter(user = request.user)
        
        

templates/authusers/changepassword.html
{% extends 'partials/base.html' %}
{% load static %}
{% block changepassword %}
<div class="Profile-tag">
    <h2 class="Profile-h2">Profile</h2>
</div>
<div class="profile-container">
    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="about">
                        <h5>About</h5>
                        <p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>
                    </div>
                    <br><br>
                    <div class="aside" >
                        <hr>
                        <a href="{% url 'authusers:user-profile' %}" class="w3-bar-item w3-button">User Profile Password</a><br>
                        <hr>
                        <a href="{% url 'authusers:user_change_pass' %}" class="w3-bar-item w3-button">Change Password</a><br>
                        <hr>
                        <a href="{% url 'authusers:user_orders' %}" class="w3-bar-item w3-button" >Orders</a><br>
                        <hr>
                        <a href="#" class="w3-bar-item w3-button">Address</a>
                        <hr>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <form action="" method="POST">
                {% csrf_token %}
            <div class="row gutters">
                
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <h6 class="mb-2 text-primary">Personal Details</h6>
                </div>
                <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                    
                        <div class="form-group">
                            <label for="{{ form.new_password1.id_for_label }}">New Password</label>
                            <input type="password" class="form-control" id="{{ form.new_password1.id_for_label }}" name="{{ form.new_password1.name }}" placeholder="Enter new password"> 
                            <small class="text-danger">{{ form.new_password1.errors|striptags }}</small><br>
                        <div class="form-group">
                            <label for="{{ form.new_password2.id_for_label }}">Confirm Password</label>
                            <input type="password" class="form-control" id="{{ form.new_password2.id_for_label }}" name="{{ form.new_password2.name }}" placeholder="Confirm new password"> 
                            <small class="text-danger">{{ form.new_password2.errors|striptags }}</small><br>
                        </div>
                        {% if form.non_field_errors %}
                        {% for error in form.non_field_errors %}
                        <p class="alert alert-danger my-3">{{error}}</p>
                        {% endfor %}
                        {% endif %}
                </div>
                
            </div>
            
            <div class="row gutters">
                <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                    <div class="text-right">
                        <input type="submit" value="Update Password" class="btn btn-daark" style="background-color: #D10024; color: white;"> <br>
                    </div>
                </div>
            </div>
        </form>
        </div>
    </div>
    </div>
    </div>
    </div> 
    
{% endblock changepassword %}

    

templates/authusers/login.html
{% extends 'authusers/base.html' %}
{% load static %}

{% block content %}
<h1>SignIn Form</h1>

<form action="" method="POST" novalidate>
    {% csrf_token %}

    <!-- Email input -->
    <div class="form-outline mb-4">
        <input type="email" id="form3Example3" class="form-control" name="{{ form.username.name }}" />
        <label class="form-label" for="form3Example3">{{ form.username.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
        <small class="text-error">{{ form.username.errors|striptags }}</small>
    </div>

    <!-- Password input -->
    <div class="form-outline mb-4">
        <input type="password" id="form3Example4" class="form-control" name="{{ form.password.name }}" />
        <label class="form-label" for="form3Example4">{{ form.password.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
        <small class="text-error">{{ form.password.errors|striptags }}</small>
    </div>

    <!-- Submit button -->
    <p>Don't have an account?<a href="{% url 'authusers:sign-up' %}" style="color: black; font-style: italic;"> Sign Up</a></p>
    <button type="submit" class="btn btn-dark btn-block mb-4">Sign In</button>
    <div style="text-align: right;">
        <a href="{% url 'coreapp:index' %}" class="btn btn-dark mt-3">Back to Website</a>
    </div>
    <br>

    <!-- authetication errors -->

    {% if form.non_field_errors %}
    <div class="alert alert-danger">
        {{ form.non_field_errors }}
    </div>
    {% endif %}
    <!-- end auth errors -->
    <br>

    <!-- user defind errors -->
    {% if messages %}
    {% for message in messages %}
    <div class="alert alert-{{message.tags}}"id="errorAlert" role="alert">
		{{message}}
	</div>
    {% endfor %}
    {% endif %}
    <!-- end user defind errors -->
    
        


</form>

{% endblock %}

templates/authusers/orderdetails.html
{% extends 'partials/base.html' %}
{% load static %}

{% block orders %}
  {% load humanize %}

  <div class="Profile-tag">
    <h2 class="Profile-h2">Profile</h2>
  </div>
  <div class="profile-container">
    <div class="row gutters">
      <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
          <div class="card-body">
            <div class="account-settings">
              <div class="user-profile">
                <div class="about">
                  <h5>About</h5>
                  <p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>
                </div>
                <br /><br />
                <div class="aside">
                  <hr />
                  <a href="{% url 'authusers:user-profile' %}" class="w3-bar-item w3-button">User Profile Password</a><br />
                  <hr />
                  <a href="{% url 'authusers:user_change_pass' %}" class="w3-bar-item w3-button">Change Password</a><br />
                  <hr />
                  <a href="{% url 'authusers:user_orders' %}" class="w3-bar-item w3-button">Orders</a><br />
                  <hr />
                  <a href="#" class="w3-bar-item w3-button">Address</a>
                  <hr />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
          <div class="card-body">
            <div class="table-container">
              <div class="table-responsive">
                <table class="table centered-table">
                  <thead>
                    <tr>
                      <th>Invoice #</th>
                      <th>Product</th>
                      <th>Color</th>
                      <th>Qty</th>
                      <th>Price</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% if products %}
                      {% for product in products %}
                        <tr>
                          <td>{{ product.invoice_no }}</td>
                          <td>{{ product.item }}</td>
                          <td>{{ product.color }}</td>
                          <td>{{ product.qty }}</td>
                          <td>{{ product.price }}</td>
                          <td>
                            <a href="" class="btn btn-primary" style="background-color: #D10024; color: white;">View Order</a>
                          </td>
                        </tr>
                      {% endfor %}
                    {% else %}
                      <strong><i>No records Found</i></strong>
                    {% endif %}
                  </tbody>
                </table>
              </div>
              <div class="text-right">
                {% comment %} <input type="submit" value="Update Password" class="btn btn-dark" style="background-color: #D10024; color: white;" /> {% endcomment %}
                <a href="{% url 'authusers:user_orders' %}" class="btn btn-dark" style="background-color: #D10024; color: white;">Back</a><br />
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/authusers/orders.html
{% extends 'partials/base.html' %}
{% load static %}

{% block orders %}
{% load humanize %}

  <div class="Profile-tag">
    <h2 class="Profile-h2">Profile</h2>
  </div>
  <div class="profile-container">
    <div class="row gutters">
      <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
          <div class="card-body">
            <div class="account-settings">
              <div class="user-profile">
                <div class="about">
                  <h5>About</h5>
                  <p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>
                </div>
                <br /><br />
                <div class="aside">
                  <hr />
                  <a href="{% url 'authusers:user-profile' %}" class="w3-bar-item w3-button">User Profile Password</a><br />
                  <hr />
                  <a href="{% url 'authusers:user_change_pass' %}" class="w3-bar-item w3-button">Change Password</a><br />
                  <hr />
                  <a href="{% url 'authusers:user_orders' %}" class="w3-bar-item w3-button">Orders</a><br />
                  <hr />
                  <a href="#" class="w3-bar-item w3-button">Address</a>
                  <hr />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
        <div class="card h-100">
          <div class="card-body">
            <div class="table-container">
              <div class="table-responsive">
                <table class="table centered-table">
                  <thead>
                    <tr>
                      <th>Invoice #</th>
                      <th>Date</th>
                      <th>Product Status</th>
                      <th>Payment Status</th>
                      <th>Total</th>
                      <th>Action</th>
                    </tr>
                  </thead>  
                  <tbody>
                    {% if orders %}
                      {% for o in orders %}
                        <tr>
                          <td>INVOICE-NO-{{ o.id }}</td>
                          <td>{{ o.order_date }}</td>
                          <td>{{ o.product_status }}</td>
                          <td>{{ o.payment_status|yesno:'Paid, Un-paid' }}</td>
                          <td>{{ o.price|floatformat:2|intcomma }}</td>
                          <td>
                            <a href="{% url 'authusers:order-detials' o.id %}" class="btn btn-primary" style="background-color: #D10024; color: white;">View Order</a>
                          </td>
                        </tr>
                      {% endfor %}
                    {% else %}
                      <strong><i>No Orders Found</i></strong>
                    {% endif %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/authusers/profile.html
{% extends 'partials/base.html' %}

{% load static %}
{% block profile %}

<div class="Profile-tag">
    <h2 class="Profile-h2">Profile</h2>
</div>
<div class="profile-container">
    <div class="row gutters">
    <div class="col-xl-3 col-lg-3 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <div class="account-settings">
                <div class="user-profile">
                    <div class="about">
                        <h5 style="color: black;">About</h5>
                        <p>I'm Yuki. Full Stack Designer I enjoy creating user-centric, delightful and human experiences.</p>
                    </div>
                    <br><br>
                    <div class="aside" >
                        <hr>
                        <a href="{% url 'authusers:user-profile' %}" class="w3-bar-item w3-button">User Profile Password</a><br>
                        <hr>
                        <a href="{% url 'authusers:user_change_pass' %}" class="w3-bar-item w3-button">Change Password</a><br>
                        <hr>
                        <a href="{% url 'authusers:user_orders' %}" class="w3-bar-item w3-button">Orders</a><br>
                        <hr>
                        <a href="#" class="w3-bar-item w3-button">Address</a>
                        <hr>
                    </div>
                </div>
                
            </div>
        </div>
    </div>
    </div>
    <div class="col-xl-9 col-lg-9 col-md-12 col-sm-12 col-12">
    <div class="card h-100">
        <div class="card-body">
            <form action="" method="POST" novalidate>
                {% csrf_token %}
                <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <h6 class="mb-2 text-primary">Personal Details</h6>
                    </div>
                    <div class="col-xl-6 col-lg-6 col-md-6 col-sm-6 col-12">
                        <div class="form-group">
                            <label for="{{ form.username.id_for_label }}">Username</label>
                            <input type="text" class="form-control" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" placeholder="Username" value="{{ form.username.value }}" readonly>
                            <small class="text-danger">{{ form.username.errors|striptags }}</small>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.first_name.id_for_label }}">First Name</label>
                            <input type="text" class="form-control" id="{{ form.first_name.id_for_label }}" name="{{ form.first_name.name }}" placeholder="First Name" value="{{ form.first_name.value }}" readonly>
                            <small class="text-danger">{{ form.first_name.errors|striptags }}</small>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.last_name.id_for_label }}">Last Name</label>
                            <input type="text" class="form-control" id="{{ form.last_name.id_for_label }}" name="{{ form.last_name.name }}" placeholder="Last Name" value="{{ form.last_name.value }}" readonly>
                            <small class="text-danger">{{ form.last_name.errors|striptags }}</small>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.email.id_for_label }}">Email</label>
                            <input type="text" class="form-control" id="{{ form.email.id_for_label }}" name="{{ form.email.name }}" placeholder="Email" value="{{ form.email.value }}" readonly>
                            <small class="text-danger">{{ form.email.errors|striptags }}</small>
                        </div>
                        <div class="form-group">
                            <label for="{{ form.user_phone.id_for_label }}">Phone No</label>
                            <input type="text" class="form-control" id="{{ form.user_phone.id_for_label }}" name="{{ form.user_phone.name }}" placeholder="3xxxxxxxx" value="{{ form.user_phone.value }}" readonly>
                            <small class="text-danger">{{ form.user_phone.errors|striptags }}</small>
                        </div>
                        
                        {% if form.non_field_errors %}
                            {% for error in form.non_field_errors %}
                                <p class="alert alert-danger my-3">{{ error }}</p>
                            {% endfor %}
                        {% endif %}
                    </div>
                </div>
                {% comment %} <div class="row gutters">
                    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                        <div class="text-right">
                            <button type="button" id="submit" name="submit" class="btn btn-secondary">Cancel</button>
                            <input type="submit" value="Update Profile" class="btn btn-primary mt-4"> <br>
                        </div>
                    </div>
                </div> {% endcomment %}
            </form>            
        </div>
    </div>
    </div>
    </div>
    </div>


{% endblock profile %}

templates/authusers/signup.html
{% extends 'authusers/base.html' %}
{% load static %}
{% comment %} {% load phonenumber_fields %} {% endcomment %}

{% block content %}
  <h1>SignUp Form</h1>
  <form action="" method="POST" novalidate>
    {% csrf_token %}

    <!-- Username input -->
    <div class="form-outline mb-4">
      <input type="text" id="form3Example1" class="form-control" name="{{ form.username.name }}" />
      <label class="form-label" for="form3Example1">{{ form.username.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
      <small class="text-error">{{ form.username.errors|striptags }}</small>
    </div>
    <!--First Name -->
    <div class="form-outline mb-4">
      <input type="text" id="form3Example1" class="form-control" name="{{ form.first_name.name }}" />
      <label class="form-label" for="form3Example1">{{ form.first_name.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
      <small class="text-error">{{ form.first_name.errors|striptags }}</small>
    </div>
    <!-- last Name -->
    <div class="form-outline mb-4">
      <input type="text" id="form3Example1" class="form-control" name="{{ form.last_name.name }}" />
      <label class="form-label" for="form3Example1">{{ form.last_name.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
      <small class="text-error">{{ form.last_name.errors|striptags }}</small>
    </div>

    <!-- Email input -->
    <div class="form-outline mb-4">
      <input type="email" id="form3Example3" class="form-control" name="{{ form.email.name }}" />
      <label class="form-label" for="form3Example3">{{ form.email.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
      <small class="text-error">{{ form.email.errors|striptags }}</small>
    </div>

    <!-- user phone number  -->
    <div class="form-outline mb-4">
      <input type="tel" id="form3Example1" class="form-control" name="{{ form.user_phone.name }}" />
      <label class="form-label" for="form3Example1">{{ form.user_phone.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
      <small class="text-error">{{ form.user_phone.errors|striptags }}</small>
    </div>

    <!-- Password inputs -->
    <div class="form-outline mb-4">
      <input type="password" id="form3Example4" class="form-control" name="{{ form.password1.name }}" />
      <label class="form-label" for="form3Example4">{{ form.password1.label }}</label>
    </div>
    <div  style="color: red; text-align: left;">
        <small class="text-error">{{ form.password1.errors|striptags }}</small>
    </div>

    <!-- 2nd password -->
    <div class="form-outline mb-4">
      <input type="password" id="form3Example5" class="form-control" name="{{ form.password2.name }}" />
      <label class="form-label" for="form3Example5">{{ form.password2.label }}</label>
    </div>
    <div style="color: red; text-align: left;">
        <small class="text-error">{{ form.password2.errors|striptags }}</small>
    </div>
    

    <!-- Checkbox -->
   <p>Already Have and account?<a href="{% url 'authusers:sign-in' %}" style="color: black; font-style: italic;"> Login</a></p>

    <!-- Submit button -->
    <button type="submit" class="btn btn-dark btn-block mb-4">Sign up</button>
    <div style="text-align: right;">
        <a href="{% url 'coreapp:index' %}" class="btn btn-dark mt-3">Back to Website</a>
    </div>
    <br>
  </form>

  
{% endblock %}